name: Deploy Excel Vault

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  deploy:

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # ------------------------------------------------------
      # 1. Download repository
      # ------------------------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v6


      # ------------------------------------------------------
      # 2. Configure GitHub Pages
      # ------------------------------------------------------

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5


      # ------------------------------------------------------
      # 3. Create real config.js
      # ------------------------------------------------------

      - name: Generate config.js
        env:
          API_URL: ${{ secrets.API_URL }}

        run: |
          cat > config.js <<EOF
          "use strict";

          const APP_CONFIG = Object.freeze({
              API_URL: "$API_URL"
          });
          EOF


      # ------------------------------------------------------
      # 4. Upload website artifact
      # ------------------------------------------------------

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "."


      # ------------------------------------------------------
      # 5. Deploy
      # ------------------------------------------------------

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4